server:
  port: 8082
spring:
  devtools:
    restart:
      enabled: true
  #      additional-paths: src/main/java
  application:
    name: wxapi
  datasource:
    url: jdbc:mysql://localhost:3306/teach?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    #     使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000  #客户端超时
    lettuce:
      pool:
        max-active: 20   #最大连接数
        min-idle: 5 #最小空闲
        max-wait: 5000ms  #连接超时
        max-idle: 20   #最大空闲
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
#        namespace: public


#  profiles:
#    active: dev



