server:
  port: 8090
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  profiles:
    include: prodDB,prodMail
  application:
    name: teach
  devtools:
    restart:
      enabled: true
   #序列化的时候返回值为null 的时候不序列化
  jackson:
    default-property-inclusion: NON_EMPTY
  #配置静态资源访问路径
  resources:
    static-locations: [ 'classpath:/META-INF/resources/','classpath:/resources/','classpath:/static/','classpath:/public/','classpath:/webapp/','file:${upFile.path}' ]
  #设置最大文件上传大小， 默认是1m . 如果配置了nginx，还需要修改nginx的配置
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

upFile:
  path: "C:\\upFile\\temp\\" #存储路径

serverUrl: "http://localhost:8090/"


rsa:
  private_key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK7ba656clfJZDWikAf2mJJqVMWu0vQ9ZShi13v7j6plaQOPm34tVG71U60cOVw47wz914ejEQ5ozsvrxCnzc5xnb3aVQrOs1sUdJY9pHIdACutu/zH7RCDElaMeA3jFBh5NE00E2LHH/83iROA4UfBC/GfxUqiqe6BztZ/ggvB7AgMBAAECgYAaZSsDIp7CG7eR1SFS4mmzqHN1h+d2URJFH26R266bNUW98N6zFFqriUMBXcJW5o1Hc8YmRnpbp3yYEdYB0ys/UASX6ycA2V4Gu9vmzFOAKvYZ0KC7cAJ9H1LY8OHbPnbV0uu674+tJxFgUnfi8W6qwmU2Uy6htHWnwJiwdlrICQJBANjbkcBXxn07zWCqccr6xCI20qozvSM+r52sfYwh6u6ynWiiR+tZtgpCZGshj/DHNizjUjVF4q0gFg7z1IBOWrcCQQDOax0RmdqspUo8FtoFefaz/C+SwrVV8KjRag78f8MVYtdNM+BmDMUsZtFddnIDwSq6Df2vSzD8/Glk3/3Bx+RdAkEAjsHkrjFaWoDuz88EwDHawgdDIYaT4UrYAz1VHNYLOX3d/86s97MEErboMlpSzpfmAyDWsnlCIuQ3gTpkzt5F+wJAJ1UxzNDMYml8o8aW9MQwxksfpY+EjkO1Z3IWOPb/bWvQKt3fvJJiX/uXmX+gaia8xYc099oUE6DlVFt6Nxqn4QJAeAz/SS77MfZdfY7K4+vXVb23uK9srSADGF0aYFGtVaUkJRWMddV3/WAdyQXxGsmFFOGnxQJgqcY/9j/voWk0eA==

  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCu22uuenJXyWQ1opAH9piSalTFrtL0PWUoYtd7+4+qZWkDj5t+LVRu9VOtHDlcOO8M/deHoxEOaM7L68Qp83OcZ292lUKzrNbFHSWPaRyHQArrbv8x+0QgxJWjHgN4xQYeTRNNBNixx//N4kTgOFHwQvxn8VKoqnugc7Wf4ILwewIDAQAB
