spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teach?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000  #客户端超时
    lettuce:
      pool:
        max-active: 20   #最大连接数
        min-idle: 5 #最小空闲
        max-wait: 5000ms  #连接超时
        max-idle: 20   #最大空闲
  #@cache注解的扩展。标记了@cache 缓存的key过期时间
  cache:
    redis:
      time-to-live: 5000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
